name: $(Date:yyyy.MM.dd)$(Rev:.r)

trigger: none

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: csauer42/AzureTemplates
      endpoint: csauer42

jobs:
- job: GetVersion
  steps:
  - bash: |
      ARTVER=$(git describe)
      echo "##vso[task.setvariable variable=artver;isOutput=true]${ARTVER:1}"
    name: SetVar
- job: Stuff
  dependsOn: GetVersion
  steps:
  - template: components/version_test.yml@templates
    #variables:
    #  artver: $[ dependencies.GetVersion.outputs['SetVar.artver'] ]
    parameters:
      filename: package-name
      version: $[ dependencies.GetVersion.outputs['SetVar.artver'] ]