name: $(Date:yyyy.MM.dd)$(Rev:.r)

trigger:
- main

pr:
  drafts: false

resources:
  repositories:
    - repository: templates
      type: github
      name: csauer42/AzureTemplates
      endpoint: csauer42

variables:
  useSccache: True
  ${{ if useSccache }}:
  - group: sccache-vars
  ${{ else }}:
    CCACHE_DIR: "$(Build.SourcesDirectory)/ccache"


jobs:
- job: GetVersion
  steps:
  - bash: |
      ARTVER=$(git describe)
      echo "##vso[task.setvariable variable=artver;isOutput=true]${ARTVER:1}"
    name: SetVar
- job: Stuff
  dependsOn: GetVersion
  variables:
    artver: $[ dependencies.GetVersion.outputs['SetVar.artver'] ]
  steps:
  - template: components/version_test.yml@templates
    parameters:
      filename: package-name
      version: $(artver)
  - bash: |
      echo 'Build.Reason is '$(Build.Reason)
- job: TestVariables
  dependsOn: Stuff
  steps:
    - bash: echo 'Using sccache'
      condition: useSccache
    - bash: echo 'Using ccache'
      condition: not(useSccache)
    - script: |
        if [ ! -d $(CCACHE_DIR) ]; then
          mkdir $(CCACHE_DIR)
        fi
    - task: Cache@2
      displayName: ccache
      condition: not(useSccache)
      inputs:
        key: 'ccache | "$(Build.SourceVersion)"'
        path: $(CCACHE_DIR)
        restoreKeys: |
          ccache
