name: $(Date:yyyy.MM.dd)$(Rev:.r)

trigger:
- main

pr:
  drafts: false

resources:
  repositories:
    - repository: templates
      type: github
      name: csauer42/AzureTemplates
      endpoint: csauer42

pool:
  vmImage: ubuntu-latest

jobs:
- job: GetVersion
  container:
    image: docker.io/csauer42/cmake-builder
    endpoint: docker-hub-csauer42
  steps:
  - bash: |
      ARTVER=$(git describe)
      echo "##vso[task.setvariable variable=artver;isOutput=true]${ARTVER:1}"
    name: SetVar
- job: Stuff
  dependsOn: GetVersion
  container:
    image: docker.io/csauer42/cmake-builder
    endpoint: docker-hub-csauer42
  variables:
    artver: $[ dependencies.GetVersion.outputs['SetVar.artver'] ]
  steps:
  - template: components/version_test.yml@templates
    parameters:
      filename: package-name
      version: $(artver)
  - bash: |
      echo 'Build.Reason is '$(Build.Reason)
  - bash: |
      ls /proc/net/
      cat /proc/net/if_inet6
