trigger: main
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo 'Doing some stuff'
- template: download.yml
  parameters:
  - sampleVersion: '1.0.0'
  - mainVersion: '0.0.6'
  - avrVersion: '2.0.0-1-g0e5955b'
- script: |
    echo 'Downloaded files:'
    ls -lah $(Build.ArtifactStagingDirectory)