trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  svctag: '1.0.0'
  sampleVersion: ''
  mainVersion: ''
  avrVersion: ''

steps:
- ${{ if eq(variables['svctag'], '') }}:
  - script: echo it is true 
- ${{ if ne(variables['svctag'], '') }}:
  - script: echo it is false
- script: |
      echo 'setting variables:'
      echo '##vso[task.setvariable variable=sampleVersion]1.0.0'
      # echo '##vso[task.setvariable variable=mainVersion]'
      echo '##vso[task.setvariable variable=avrVersion]2.0.0-1-g0e5955b'
- template: download.yml
  parameters:
    ${{ if ne($[variables.sampleVersion], '') }}:
      sampleVersion: '$(sampleVersion)'
    ${{ if ne($[variables.mainVersion], '') }}:
      mainVersion: '$(mainVersion)'
    ${{ if ne($[variables.avrVersion], '') }}:
      avrVersion: '$(avrVersion)'
- script: |
    echo 'Downloaded files:'
    ls -lah $(Build.ArtifactStagingDirectory)