trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

container:
  image: cscotest.azurecr.io/mabuild:latest
  endpoint: CSCOTest  

steps:
- script: echo 'Doing some stuff'
- template: download.yml
- script: |
    echo 'Downloaded files:'
    ls -lah $(System.DefaultWorkingDirectory)/Artifacts