trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
      echo 'setting variables:'
      echo '##vso[task.setvariable variable=sampleVersion]1.0.0'
      echo '##vso[task.setvariable variable=mainVersion]1.0.0'
      echo '##vso[task.setvariable variable=avrVersion]2.0.0-1-g0e5955b'
- template: download.yml
  parameters:
    sampleVersion: $variables[sampleVersion]
    mainVersion: $variables[mainVersion]
    avrVersion: $variables[avrVersion]
- script: |
    echo 'Downloaded files:'
    ls -lah $(Build.ArtifactStagingDirectory)