trigger:
- main

pr: none

#pool:
#  vmImage: ubuntu-latest
pool: local-builds

steps:
- script: |
      echo 'setting variables:'
      echo '##vso[task.setvariable variable=sampleVersion]1.0.0'
      echo '##vso[task.setvariable variable=mainVersion]'
      echo '##vso[task.setvariable variable=avrVersion]2.0.0-1-g0e5955b'
- template: download.yml
- script: |
    echo 'Downloaded files:'
    ls -lah $(Build.ArtifactStagingDirectory)
- script: |
      ping -c 3 10.10.0.53
