trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- ${{ if eq(variables['svctag'], '') }}:
  - script: echo it is true 
- ${{ if ne(variables['svctag'], '') }}:
  - script: echo it is false
- script: |
      echo 'setting variables:'
      echo '##vso[task.setvariable variable=sampleVersion]1.0.0'
      echo '##vso[task.setvariable variable=mainVersion]'
      echo '##vso[task.setvariable variable=avrVersion]2.0.0-1-g0e5955b'
- template: download.yml
  parameters:
      sampleVersion: '$[variables.sampleVersion]'
      mainVersion: '$[variables.mainVersion]'
      avrVersion: '$[variables.avrVersion]'
- script: |
    echo 'Downloaded files:'
    ls -lah $(Build.ArtifactStagingDirectory)