trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest
#pool: local-builds

steps:
- script: |
      echo 'setting variables:'
      echo '##vso[task.setvariable variable=sampleVersion]1.0.0'
      echo '##vso[task.setvariable variable=mainVersion]'
      echo '##vso[task.setvariable variable=avrVersion]2.0.0-1-g0e5955b'
- template: download.yml
- script: |
    echo 'Downloaded files:'
    ls -lah $(Build.ArtifactStagingDirectory)
#- script: |
#      ping -c 3 10.10.0.53
#- task: AzureFileCopy@4
#  inputs:
#    SourcePath: '$(Build.ArtifactStagingDirectory)'
#    azureSubscription: 'Azure subscription 1(e348d66c-c78e-40a3-b097-3e70e49d6185)'
#    Destination: 'AzureBlob'
#    storage: 'packagestorage42'
#    ContainerName: 'packages'
- script: |
      echo 'az:'
      which az
      echo 'azcopy:'
      which azcopy
- script: |
      azcopy copy '$(Build.ArtifactStagingDirectory)/AVRCommon_2.0.0-1-g0e5955b' 'https://packagestorage42.blob.core.windows.net/packages?sp=r&st=2021-12-08T22:46:38Z&se=2021-12-09T06:46:38Z&spr=https&sv=2020-08-04&sr=c&sig=AfSoBEVR9fxeOhB0b%2FcgO1eBSrQkxRBBbAzPaNzoAtY%3D'
