trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo 'Doing some stuff'
- template: dependencies.yml
- template: download.yml
  parameters:
    dependencies: ${{ BuildDependencies }}
- script: |
    echo 'Downloaded files:'
    ls -lah $(System.DefaultWorkingDirectory)