trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo 'Doing some stuff'
- template: download.yml
- script: |
    echo 'Downloaded files:'
    ls -lah $(System.DefaultWorkingDirectory)