trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- template: deps_alt.yml
- script: echo 'OK again'

#steps:
#- task: PythonScript@0
#  inputs:
#    scriptSource: 'filePath'
#    scriptPath: 'tools/getdep.py'
#- script: echo "testvar:" $(testvar)
#- template: template.yml
#  parameters:
#    DownloadFiles: $(testvar)