trigger:
- main

pr: none

#pool:
#  vmImage: ubuntu-latest
pool: local-builds

steps:
- script: |
      echo 'setting variables:'
      echo '##vso[task.setvariable variable=sampleVersion]1.0.0'
      echo '##vso[task.setvariable variable=mainVersion]'
      echo '##vso[task.setvariable variable=avrVersion]2.0.0-1-g0e5955b'
- template: download.yml
- script: |
    echo 'Downloaded files:'
    ls -lah $(Build.ArtifactStagingDirectory)
- script: |
      ping -c 3 10.10.0.53
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(e348d66c-c78e-40a3-b097-3e70e49d6185)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage azcopy blob upload -c packages --account-name packagestorage42 -s "$(Build.ArtifactStagingDirectory)/*" --recursive'
