trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  sampleVersion: '1.0.0'
  mainVersion: '0.0.1'
  avrVersion: '1.0.0'

steps:
#- script: |
#      echo 'setting variables:'
#      echo '##vso[task.setvariable variable=sampleVersion]1.0.0'
#      echo '##vso[task.setvariable variable=mainVersion]1.0.0'
#      echo '##vso[task.setvariable variable=avrVersion]2.0.0-1-g0e5955b'
- template: download.yml
  parameters:
    sampleVersion: '$variables[sampleVersion]'
    mainVersion: '1.0.0'
    avrVersion: '$(avrVersion)'
- script: |
    echo 'Downloaded files:'
    ls -lah $(Build.ArtifactStagingDirectory)